pipeline {
    agent any

    parameters {
        booleanParam(name: 'contract_tests_only', defaultValue: false, description: 'Only Contract Tests')
        booleanParam(name: 'record_issues', defaultValue: true, description: 'Record issues')
        choice(name: 'build_status', choices: ['DEFAULT', 'SUCCESS', 'UNSTABLE', 'FAILURE'],
                description: 'Force build status')
    }

    environment {
        WORKSPACE_PATH = "${env.WORKSPACE}/app-error-handling"
        INTEGRATION_BRANCH = 'jenkins-code-warnings'
        INTEGRATION_REFERENCE_JOB_NAME = 'pipeline-multibranch-1/jenkins-code-warnings'
        IGNORE_QUALITY_GATE = "${env.BRANCH_NAME != INTEGRATION_BRANCH}"
    }
    tools {
        gradle 'gradle-6.3'
    }

    stages {
        stage('Common Steps') {
            stages {
                stage('Grade Clean') {
                    steps {
                        sh "gradle -b ./app-error-handling/build.gradle clean"
                    }
                }
            }
        }

        stage('Testing') {
            stages {
                stage('Component Testing') {
                    when { equals expected: false, actual: params.contract_tests_only }
                    stages {
                        stage('Bugs Analysis - Spotbugs') {
                            steps {
                                sh "gradle -b ./app-error-handling/build.gradle spotbugsMain --info"
                            }
                        }
                        stage('Duplicated Code Analysis - cpd') {
                            steps {
                                sh "gradle -b ./app-error-handling/build.gradle cpdCheck --info"
                            }
                        }
                        stage('Static Code - pmd') {
                            steps {
                                sh "gradle -b ./app-error-handling/build.gradle pmdMain --info"
                            }
                        }
                        stage('Style Analysis - CheckStyle') {
                            steps {
                                sh "gradle -b ./app-error-handling/build.gradle checkstyleMain --info"
                                sh "gradle -b ./app-error-handling/build.gradle checkstyleTest --info"
                            }
                        }
                        stage('Unit Test') {
                            steps {
                                sh "gradle -b ./app-error-handling/build.gradle test --info"
                            }
                        }
                    }
                }

                stage('Code Coverage Analysis') {
                    steps {
                        sh "gradle -b ./app-error-handling/build.gradle jacocoTestReport --info"
                    }
                }
            }
            post {
                always {
                    dir("${WORKSPACE_PATH}") {
                        script {
                            if (params.record_issues) {
                                echo 'Record code style and quality issues'

                                def refBuild = selectRun job: INTEGRATION_REFERENCE_JOB_NAME,
                                        selector: permalink('lastSuccessfulBuild'),
                                        filter: parameters('contract_tests_only=false'), verbose: true
                                def refBuildId = refBuild.getId()

                                recordIssues(
                                        enabledForFailure: true,
                                        ignoreQualityGate: IGNORE_QUALITY_GATE,
                                        referenceJobName: INTEGRATION_REFERENCE_JOB_NAME,
                                        tool: pmdParser(pattern: 'build/reports/pmd/pmd.xml'),
                                        referenceBuildId: refBuildId,
                                        unstableNewAll: 1)
                                recordIssues(
                                        enabledForFailure: true,
                                        ignoreQualityGate: IGNORE_QUALITY_GATE,
                                        referenceJobName: INTEGRATION_REFERENCE_JOB_NAME,
                                        tool: spotBugs(pattern: 'build/reports/spotbugs/spotbugsMain.xml'),
                                        referenceBuildId: refBuildId,
                                        unstableNewAll: 1);
                                recordIssues(
                                        enabledForFailure: true,
                                        ignoreQualityGate: IGNORE_QUALITY_GATE,
                                        referenceJobName: INTEGRATION_REFERENCE_JOB_NAME,
                                        tool: cpd(pattern: 'build/reports/cpd/cpd.xml'),
                                        referenceBuildId: refBuildId,
                                        unstableNewAll: 1);
                                recordIssues(
                                        enabledForFailure: true,
                                        ignoreQualityGate: IGNORE_QUALITY_GATE,
                                        referenceJobName: INTEGRATION_REFERENCE_JOB_NAME,
                                        tool: checkStyle(pattern: 'build/reports/checkstyle/checkstyle*.xml'),
                                        referenceBuildId: refBuildId,
                                        unstableNewAll: 1);
                                jacoco(
                                        execPattern: 'build/jacoco/*.exec',
                                        classPattern: 'build/classes/',
                                        exclusionPattern: './**/test/',
                                        sourcePattern: 'src/main/'
                                )
                                archive 'build/jacoco/**/*.xml'
                                junit 'build/test-results/**/*.xml'
                            }

                            if (params.build_status != 'DEFAULT') {
                                currentBuild.result = params.build_status
                            }
                        }
                    }
                }
            }
        }
    }
}